import Head from "next/head";
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Form from "../components/Form";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Emial send</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Form />
    </div>
  );
}
